# Menu
menu:
  home:
    url: /
    icon: home
  archive:
    url: /archives
    icon: briefcase

# Comments
disqus:
  embed: 
  count: 

#Months
months:
  - january
  - february
  - march
  - april
  - may
  - june
  - july
  - august
  - september
  - october
  - november
  - december

# Highlight theme
highlight_theme: atom-one-dark