# Menu
menu:
  home:
    url: /
    icon: home
  about:
    url: /acerca-de
    icon: person
  archive:
    url: /archivo
    icon: briefcase

# Comments
disqus:
  embed: 
  count: 

#Months
months:
  - january
  - february
  - march
  - april
  - may
  - june
  - july
  - august
  - september
  - october
  - november
  - december