# Menu items
home: Blog
about: Acerca de mí
archive: Archivo

# Blog strings
blog_archive: Archivo del blog
read_more: Leer más
tag_content: Contenido con la etiqueta %s

# Paginator
next: Siguiente
prev: Anterior

# Months
january: Enero
febrary: Febrero
march: Marzo
april: Abril
may: Mayo
june: Junio
july: Julio
august: Agosto
september: Septiembre
october: Octubre
november: Noviembre
december: December